version: "3"
services:
  sqlite3:
    container_name: sqlite
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - sqlite:/data/db/
    ports:
      - "32000:3306"
  redis:
    image: redis:5.0.5
    ports:
      - "6379:6379"
    volumes:
      - redis:/data/redis
  flask:
    container_name: amo-storage
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ${CONFIG_PATH}:/app/config.ini:Z
    entrypoint: python
    command: main.py --config_path /app/config.ini --host 0.0.0.0 --port 5000
volumes:
  sqlite:
  redis:
