version: "3"
services:
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_USER: amo
      MYSQL_PASSWORD: replaced
      MYSQL_DATABASE: amo_storage
      MYSQL_ROOT_PASSWORD: replaced
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
  redis:
    image: redis:5.0.5
    ports:
      - "6379:6379"
    volumes:
      - redis:/data/redis
#  flask:
#    container_name: amo-storage
#    build: .
#    ports:
#      - ${PORT}:5000
#    volumes:
#      - ${CONFIG_DIR}:/app/config:z
#    entrypoint: python3
#    command: main.py --config_dir /app/config --host 0.0.0.0 --port 5000
volumes:
  mariadb:
  redis:
